#!/usr/bin/env python3
"""Generate js/data/elements.js from the open Periodic-Table-JSON dataset.

Usage:
    python3 scripts/build-elements.py                 # download the dataset
    python3 scripts/build-elements.py path/to.json    # use a local copy

Data source: https://github.com/Bowserinator/Periodic-Table-JSON
(values compiled from Wikipedia; see that repository for its license).
"""
import json
import os
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/Bowserinator/Periodic-Table-JSON/master/PeriodicTableJSON.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "js", "data", "elements.js")


def first(values):
    return values[0] if values else None


def radius(radii):
    if not radii:
        return None
    return first(radii.get("empirical")) or first(radii.get("calculated"))


def slim(e):
    return {
        "number": e["number"],
        "symbol": e["symbol"],
        "name": e["name"],
        # Some masses carry the uncertainty digit appended (e.g. 55.8452); 3 decimals is plenty.
        "mass": round(e["atomic_mass"], 3),
        "category": e["category"],
        "group": e["group"],
        "period": e["period"],
        "block": e["block"],
        "x": e["xpos"],
        "y": e["ypos"],
        "phase": e["phase"],
        "shells": e["shells"],
        "config": e["electron_configuration_semantic"],
        "en": e["electronegativity_pauling"],
        "radius": radius(e.get("atomic_radii")),
        "ie1": first(e.get("ionization_energies")),
        "ea": e.get("electron_affinity"),
        "melt": e.get("melt"),
        "boil": e.get("boil"),
        "density": e.get("density"),
        "densityUnit": e.get("density_unit"),
        "appearance": e.get("appearance"),
        "discoveredBy": e.get("discovered_by"),
        "color": e.get("cpk-hex"),
        "summary": e.get("summary"),
        "source": e.get("source"),
    }


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as f:
            data = json.load(f)
    else:
        with urllib.request.urlopen(URL) as r:
            data = json.load(r)
    elements = [slim(e) for e in data["elements"] if e["number"] <= 118]
    body = json.dumps(elements, ensure_ascii=False, separators=(",", ":"))
    body = body.replace("},{", "},\n{")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build-elements.py — do not edit by hand.\n")
        f.write("// Source: https://github.com/Bowserinator/Periodic-Table-JSON (data from Wikipedia).\n")
        f.write("(function (root) {\n  var ELEMENTS = ")
        f.write(body)
        f.write(";\n  if (typeof module !== 'undefined' && module.exports) module.exports = ELEMENTS;\n")
        f.write("  else root.ELEMENTS = ELEMENTS;\n})(this);\n")
    print(f"Wrote {len(elements)} elements to {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
